<?php

return [
    'USD' => 'US Dollar ($)',
    'EUR' => 'Euro (€)',
    'GBP' => 'British Pound (£)',
    'JPY' => 'Japanese Yen (¥)',
    'CAD' => 'Canadian Dollar (C$)',
    'AUD' => 'Australian Dollar (A$)',
    'CHF' => 'Swiss Franc (CHF)',
    'CNY' => 'Chinese Yuan (¥)',
    'INR' => 'Indian Rupee (₹)',
    'BRL' => 'Brazilian Real (R$)',
    'ZAR' => 'South African Rand (R)',
    'MXN' => 'Mexican Peso ($)',
    'RUB' => 'Russian Ruble (₽)',
    'KRW' => 'South Korean Won (₩)',
    'NZD' => 'New Zealand Dollar (NZ$)',
    'SEK' => 'Swedish Krona (kr)',
    'NOK' => 'Norwegian Krone (kr)',
    'DKK' => 'Danish Krone (kr)',

    'PLN' => 'Polish Zloty (zł)',
    'TRY' => 'Turkish Lira (₺)',
    'AED' => 'United Arab Emirates Dirham (د.إ)',
    'SAR' => 'Saudi Riyal (ر.س)',
    'THB' => 'Thai Baht (฿)',
    'IDR' => 'Indonesian Rupiah (Rp)',
    'MYR' => 'Malaysian Ringgit (RM)',
    'PHP' => 'Philippine Peso (₱)',
    'SGD' => 'Singapore Dollar (S$)',
    'HKD' => 'Hong Kong Dollar (HK$)',
    'TWD' => 'New Taiwan Dollar (NT$)',
    'BTC' => 'Bitcoin (₿)',
    'ETH' => 'Ethereum (Ξ)',
    'XRP' => 'Ripple (XRP)',
    'LTC' => 'Litecoin (Ł)',
    'BCH' => 'Bitcoin Cash (₿)',
    'DOT' => 'Polkadot (DOT)',
    'ADA' => 'Cardano (₳)',
    'SOL' => 'Solana (SOL',
    'XLM' => 'Stellar (XLM)',

    'LINK' => 'Chainlink (LINK)',
];
